---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: helm-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          resources:
            requests: { memory: "256Mi", cpu: "200m" }
            limits:   { memory: "512Mi", cpu: "500m" }
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: helm-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests: { memory: "64Mi",  cpu: "50m"  }
            limits:   { memory: "128Mi", cpu: "100m" }