apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: helm-checker
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: linter-service
  namespace: helm-checker
spec:
  selector:
    app: linter
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP